apiVersion: v1
kind: Service
metadata:
  name: fragments
  namespace: {%= namespace %}-prod
spec:
  ports:
  - name: "http"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: fragments
