apiVersion: v1
kind: Service
metadata:
  name: varnish
  namespace: {%= namespace %}-prod
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: varnish
