apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authorization-api
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: authorization-api
        env: prod
    spec:
      nodeSelector:
        milescloud/node-type: normal
      containers:
      - name: authorization-api
        image: miles-nocms.jfrog.io/authorization_api:${DOCKER_TAG}
        env:
          - name: NODE_ENV
            value: prod
          - name: CRYPTEX_KEYSOURCE_PLAINTEXT_KEY
            valueFrom:
              secretKeyRef:
                name: nocms-secrets
                key: cryptex-keysource-key
          - name: CONFIG_API_HOST
            valueFrom:
              configMapKeyRef:
                name: nocms-config
                key: config-api-host
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 10Mi
      imagePullSecrets:
      - name: gcr-registry
