apiVersion: v1
kind: Service
metadata:
  name: authorization-api
  namespace: miles-no-prod
spec:
  ports:
  - name: "http"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: authorization-api
