apiVersion: v1
kind: Service
metadata:
  name: config-api
  namespace: {%= namespace %}-prod
spec:
  ports:
  - name: "http"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: config-api
